### ISSUE TITLE
Add a magic function to call sdk methods directly

### ISSUE THREAD

**Issue by sicaboy** [joshuapack/laravel-cloudflare#2]
Can we have a magic method to proxy any undefined method but callable in cloudflare SDK

**Comment by joshuapack** [comment]
I like that idea. I'll see about adding that this week

**Comment by joshuapack** [comment]
You should now have full access to all EndPoints API from the SDK

https://github.com/joshuapack/laravel-cloudflare/releases/tag/v0.3.2
